#!/bin/sh

set -e

# We need to be root here ...
for locale in 'en_US.UTF-8 UTF-8'; do
  sed -i -e "0,/^[# ]*$locale *$/ s/^[# ]*$locale *$/$locale/" /etc/locale.gen
done
locale-gen

# ... but not here
cd Horde_Core*/test/./Horde/Core
su www-data --preserve-environment --shell /bin/sh --command 'phpunit -v .'
